import * as fs from 'fs/promises'
import * as path from 'path'

export interface RepoConventions {
  branch: {
    pattern: string
    maxLength: number
    mustContainHyphen: boolean
    slugMaxLength: number
  }
  commit: {
    format: string
    defaultType: string
    defaultScope: string
    allowedTypes: string[]
    maxDescriptionLength: number
  }
  pr: {
    titleFormat: string
    bodyTemplate: string
  }
  git: {
    deleteLocalBranchOnConflict: boolean
    deleteRemoteBranchOnConflict: boolean
    forceCreateBranch: boolean
  }
}

const DEFAULT_CONVENTIONS: RepoConventions = {
  branch: {
    pattern: 'agent-{slug}-{shortId}',
    maxLength: 40,
    mustContainHyphen: true,
    slugMaxLength: 20,
  },
  commit: {
    format: '{type}({scope}): {description}',
    defaultType: 'feat',
    defaultScope: 'agent',
    allowedTypes: ['feat', 'fix', 'hotfix', 'docs', 'style', 'refactor', 'test', 'chore', 'ci', 'perf', 'wip'],
    maxDescriptionLength: 72,
  },
  pr: {
    titleFormat: '[Agent] {task}',
    bodyTemplate: '## Summary\n\n{explanation}\n\n---\n*Generated by Mac Agent*',
  },
  git: {
    deleteLocalBranchOnConflict: true,
    deleteRemoteBranchOnConflict: true,
    forceCreateBranch: true,
  },
}

let cachedConventions: RepoConventions | null = null

export async function loadConventions(): Promise<RepoConventions> {
  if (cachedConventions) return cachedConventions

  try {
    const configPath = path.join(import.meta.dirname, '..', 'repo-conventions.json')
    const content = await fs.readFile(configPath, 'utf-8')
    const parsed = JSON.parse(content)
    cachedConventions = { ...DEFAULT_CONVENTIONS, ...parsed }
  } catch (e) {
    console.log('[Conventions] Using default conventions')
    cachedConventions = DEFAULT_CONVENTIONS
  }
  return cachedConventions!
}

export function getConventions(): RepoConventions {
  return cachedConventions || DEFAULT_CONVENTIONS
}

// Format commit message according to conventions
export function formatCommitMessage(task: string, conventions?: RepoConventions): string {
  const conv = conventions || getConventions()
  const description = task
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .slice(0, conv.commit.maxDescriptionLength)

  return conv.commit.format
    .replace('{type}', conv.commit.defaultType)
    .replace('{scope}', conv.commit.defaultScope)
    .replace('{description}', description)
}

// Format PR title according to conventions
export function formatPRTitle(task: string, conventions?: RepoConventions): string {
  const conv = conventions || getConventions()
  return conv.pr.titleFormat.replace('{task}', task)
}

// Format PR body according to conventions
export function formatPRBody(explanation: string, conventions?: RepoConventions): string {
  const conv = conventions || getConventions()
  return conv.pr.bodyTemplate.replace('{explanation}', explanation)
}
